Lean/Areas/LeanManage/Controllers/CommonCommentController.cs
using Microsoft.Practices.Unity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WGX.Lean.BizEntity.Condition;
using WGX.Lean.BizEntity.Enums;
using WGX.Lean.DbEntity;
using WGX.Lean.IBiz;
using WGX.Common.Helper;
using System.IO;
using WGX.Site.Common;
using System.Diagnostics;
using Lean.Filters;

namespace Lean.Areas.LeanManage.Controllers
{
    public class CommonCommentController : PrivateController
    {
        [Dependency]
        public ICommonComment CommonCommentBiz
        {
            get;
            set;
        }

        [Dependency]
        public IListCommonComment ListCommonCommentBiz
        {
            get;
            set;
        }

        public ActionResult Index(CommonCommentCondition condition)
        {
            if (string.IsNullOrWhiteSpace(condition.ModuleCode))
            {
                condition.ModuleCode = "None";
            }
            CommonCommentBiz.ModuleCode = condition.ModuleCode.ToEnum(CommonCommentModuleCodeEnum.None);
            if (CommonCommentBiz.ModuleCode != CommonCommentModuleCodeEnum.None && ListCommonCommentBiz.CodeList.Contains(CommonCommentBiz.ModuleCode.ToString()))
            {
                ListCommonCommentBiz.ModuleCode = CommonCommentBiz.ModuleCode;
                var datas = ListCommonCommentBiz.Search(condition);
                var model = PDM.Create(datas, condition);
                return View(model);
            }
            return RedirectToAction("Create", new { moduleCode = condition.ModuleCode });
        }

        public ActionResult Create(string moduleCode = "None")
        {
            if (string.IsNullOrWhiteSpace(moduleCode))
            {
                moduleCode = "None";
            }
            CommonCommentBiz.ModuleCode = moduleCode.ToEnum(CommonCommentModuleCodeEnum.None);
            CommonComment entity = null;
            if (CommonCommentBiz.ModuleCode != CommonCommentModuleCodeEnum.None)
            {
                //如果是非列表模块, 则要到数据库取值
                if (!ListCommonCommentBiz.CodeList.Contains(CommonCommentBiz.ModuleCode.ToString()))
                {
                    entity = CommonCommentBiz.GetByCode(moduleCode);
                }

                if (null == entity)
                {
                    entity = new CommonComment { ModuleCode = moduleCode };
                }
            }
            else
            {
                SetMessage("模块代码错误!");
                entity = new CommonComment();
            }
            return View(entity);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(CommonComment entity)
        {
            if (string.IsNullOrWhiteSpace(entity.ModuleCode))
            {
                entity.ModuleCode = "None";
            }
            CommonCommentBiz.ModuleCode = entity.ModuleCode.ToEnum(CommonCommentModuleCodeEnum.None);
            if (CommonCommentBiz.ModuleCode != CommonCommentModuleCodeEnum.None)
            {
                if (!ListCommonCommentBiz.CodeList.Contains(entity.ModuleCode))
                {
                    if (entity.ID == 0)
                    {
                        CommonCommentBiz.Add(entity);
                    }
                    else
                    {
                        CommonCommentBiz.Edit(entity);
                    }
                }
                else
                {
                    ListCommonCommentBiz.ModuleCode = CommonCommentBiz.ModuleCode;
                    if (entity.ID == 0)
                    {
                        ListCommonCommentBiz.Add(entity);
                    }
                    else
                    {
                        ListCommonCommentBiz.Edit(entity);
                    }
                }

                if (!CommonCommentBiz.HasError && !ListCommonCommentBiz.HasError)
                {
                    SetMessage("保存成功!");
                    if (entity.ID > 0)
                    {
                        entity = CommonCommentBiz.GetByCode(entity.ModuleCode);
                    }
                }
                else
                {
                    ParseBizError(CommonCommentBiz);
                    ParseBizError(ListCommonCommentBiz);
                }
            }
            else
            {
                SetMessage("模块代码错误!");
            }
            return View(entity);
        }

        public ActionResult Edit(long id, string moduleCode = "None")
        {
            if (string.IsNullOrWhiteSpace(moduleCode))
            {
                moduleCode = "None";
            }
            ListCommonCommentBiz.ModuleCode = moduleCode.ToEnum(CommonCommentModuleCodeEnum.None);
            CommonComment entity = null;
            if (ListCommonCommentBiz.ModuleCode != CommonCommentModuleCodeEnum.None && ListCommonCommentBiz.CodeList.Contains(ListCommonCommentBiz.ModuleCode.ToString()))
            {
                entity = ListCommonCommentBiz.GetById(id);
                if (null == entity || (null != entity && entity.ModuleCode != ListCommonCommentBiz.ModuleCode.ToString()))
                {
                    SetMessage("模块代码错误!");
                    entity = new CommonComment();
                }
                if (null == entity)
                {
                    entity = new CommonComment() { ModuleCode = moduleCode };
                }
            }
            else
            {
                SetMessage("模块代码错误!");
                entity = new CommonComment();
            }
            return View("Create", entity);
        }

        public ActionResult Delete(long id, string moduleCode = "None")
        {
            if (string.IsNullOrWhiteSpace(moduleCode))
            {
                moduleCode = "None";
            }
            var msg = "";
            var result = false;
            CommonCommentBiz.ModuleCode = moduleCode.ToEnum(CommonCommentModuleCodeEnum.None);
            var model = ListCommonCommentBiz.GetById(id);
            if (model != null && model.ModuleCode == CommonCommentBiz.ModuleCode.ToString())
            {
                if (ListCommonCommentBiz.Delete(id))
                {
                    result = true;
                    SetMessage("删除成功!");
                }
                else
                {
                    msg = ListCommonCommentBiz.Errors.FirstOrDefault().Value;
                }
            }
            else
            {
                msg = "模块代码错误!";
            }

            return Json(new { success = result, message = msg }, JsonRequestBehavior.AllowGet);

        }

        [CheckPower(false, Order= 12)]
        public ActionResult UploadOfficeFile(string ModuleCode = "None")
        {
            var msg = "";
            var result = false;
            var officeUrl = "";
            var flashUrl = "";
            var p2fPath = ConfigHelper.P2FServerPath;
            if (string.IsNullOrWhiteSpace(ModuleCode))
            {
                ModuleCode = "None";
            }
            CommonCommentBiz.ModuleCode = ModuleCode.ToEnum(CommonCommentModuleCodeEnum.None);

            if (CommonCommentBiz.ModuleCode == CommonCommentModuleCodeEnum.None)
            {
                msg = "模块代码错误!";
            }
            else
            {
                if (Request.Files.Count > 0 && Request.Files[0] != null)
                {
                    string basePath = AppDomain.CurrentDomain.BaseDirectory;
                    if (basePath.Trim().EndsWith("\\"))
                    {
                        basePath = basePath.Substring(0, basePath.Length - 1);
                    }
                    string uploadFilePath = ConfigHelper.UploadFilePath;
                    string swfFilePath = ConfigHelper.ConvertSwfPath;
                    string saveOfficeFilePath = basePath + uploadFilePath;
                    string saveSwfFilePath = basePath + swfFilePath;

                    saveOfficeFilePath = saveOfficeFilePath.Replace("/", "\\");
                    saveSwfFilePath = saveSwfFilePath.Replace("/", "\\");

                    if (!Directory.Exists(saveOfficeFilePath))
                    {
                        Directory.CreateDirectory(saveOfficeFilePath);
                    }

                    if (!Directory.Exists(saveSwfFilePath))
                    {
                        Directory.CreateDirectory(saveSwfFilePath);
                    }

                    string fileName = Request.Files[0].FileName;
                    
                    string tmpName = fileName.Substring(0, fileName.LastIndexOf("."));
                    string officeExt = Path.GetExtension(fileName);
                    int index = 1;
                    while (System.IO.File.Exists(saveOfficeFilePath + tmpName + officeExt))
                    {
                        tmpName = fileName.Substring(0, fileName.LastIndexOf(".")) + "(" + index.ToString() + ")";
                        index++;
                    }

                    string officeFileUrl = uploadFilePath + tmpName + officeExt;

                    Request.Files[0].SaveAs(saveOfficeFilePath + tmpName + officeExt);

                    string swfTmpname = tmpName;
                    //swfTmpname = swfTmpname.Substring(0, swfTmpname.LastIndexOf("."));
                    string ext = ".swf";
                    index = 1;
                    while (System.IO.File.Exists(saveSwfFilePath + swfTmpname + ext))
                    {
                        swfTmpname = swfTmpname + "(" + index.ToString() + ")";
                        index++;
                    }

                    Process.Start(p2fPath, string.Format("\"{0}\" \"{1}\"", saveOfficeFilePath + tmpName + officeExt, saveSwfFilePath + swfTmpname + ext));

                    officeUrl = tmpName + officeExt;
                    flashUrl = swfTmpname + ext;
                    result = true;
                }

Lean/Areas/LeanManage/Views/CommonComment/Create.cshtml
@model CommonComment
@{
    ViewBag.Title = "Create";
    var datas = PageDatas.GetInstance();
    var content = Model != null ? Model.DiscussContent : "";
    var controller = ViewContext.RouteData.Values["controller"].ToString();
    var action = ViewContext.RouteData.Values["action"].ToString();
    var ctrl = ViewContext.Controller as Lean.Areas.LeanManage.Controllers.CommonCommentController;
}
@Styles.Render("~/Content/ueditor/themes/iframe.css")
@using (Html.BeginForm("Create", controller, FormMethod.Post, new { id = "mainForm" }))
{
    @Html.HiddenFor(m => m.ID)
    <div class="container">
        @Html.HiddenFor(m => m.ModuleCode)
        <div class="select_type row">
            @Html.DropDownBlockFor(m => m.DiscussType, datas.GetEnumList(typeof(DiscussTypeEnum)), "col-xs-4")
            @Html.TextBlockFor(m => m.DiscussTitle, "col-xs-6")
        </div>
        <div class="row" id="input_div" style="display:none;">
            <!--输入的内容-->
            <textarea style="width: 100%; height: 600px;" rows="20" id="discuss_content">@(content)</textarea>
        </div>
        <div class="row" id="upload_div" style="display:none;">
            <!--文件选择-->
            @Html.HiddenFor(m => m.DiscussFileUrl)
            @Html.FileUploadBlockFor(m => m.DiscussOfficeFileUrl, "col-xs-4", "120px", "", "30px", null, true, "upload_file")
        </div>

        <div class="panel-footer center">
            <div class="btn-group btn-group-sm">
                <button type="button" name="btnSave" class="btn btn-primary" value="Save" id="btnSave"><span>保存</span></button>
                @if (ctrl.ListCommonCommentBiz.CodeList.Contains(Model.ModuleCode))
                {
                    <input type="button" onclick="IndexPageHelper.GoToIndex('@Url.Action("Index")?ModuleCode=@(Model.ModuleCode)')" class="btn btn-default" value="返回列表" />
                }
            </div>
        </div>
    </div>
}

@section scripts{
<script src="~/Content/ueditor/ueditor.config.js"></script>
<script src="~/Content/ueditor/ueditor.all.js"></script>
<script src="~/Content/ueditor/lang/zh-cn/zh-cn.js"></script>
    <script>
        $(function () {
            CommonCommentPageCreate = window.CommonCommentPageCreate || {};
            (function (_) {
                _.ChangeSelect = function (obj) {
                    if ($(obj).val() == '1') {
                        $("#input_div").show();
                        $("#upload_div").hide();
                    } else {
                        $("#input_div").hide();
                        $("#upload_div").show();
                    }
                }

                _.PageLoad = function () {
                    mainUE = UE.getEditor('discuss_content', {
                        toolbars: [[
                        'fullscreen', 'source', '|', 'undo', 'redo', '|',
                        'bold', 'italic', 'underline', 'fontborder', 'strikethrough', 'superscript', 'subscript', 'removeformat', 'formatmatch', 'autotypeset', 'blockquote', 'pasteplain', '|', 'forecolor', 'backcolor', 'insertorderedlist', 'insertunorderedlist', 'selectall', 'cleardoc', '|',
                        'rowspacingtop', 'rowspacingbottom', 'lineheight', '|',
                        'customstyle', 'paragraph', 'fontfamily', 'fontsize', '|',
                        'directionalityltr', 'directionalityrtl', 'indent', '|',
                        'justifyleft', 'justifycenter', 'justifyright', 'justifyjustify', '|', 'touppercase', 'tolowercase', '|',
                        'link', 'unlink', 'anchor', '|', 'imagenone', 'imageleft', 'imageright', 'imagecenter', '|',
                        'simpleupload', 'insertimage', 'emotion', 'scrawl', 'insertvideo', 'music', 'attachment', 'map', 'gmap', 'insertframe', 'insertcode', 'webapp', 'pagebreak', 'template', 'background', '|',
                        'horizontal', 'date', 'time', 'spechars', 'snapscreen', 'wordimage', '|',
                        'inserttable', 'deletetable', 'insertparagraphbeforetable', 'insertrow', 'deleterow', 'insertcol', 'deletecol', 'mergecells', 'mergeright', 'mergedown', 'splittocells', 'splittorows', 'splittocols', 'charts', '|',
                        'preview', 'searchreplace', 'help'
                        ]]
                    });
                    @*mainUE.ready(function () {
                        mainUE.setContent("@(content)");
                    });*@

                    $("#btnSave").click(function () {
                        var discussType = $("#DiscussType").val();
                        var discussTitle = $("#DiscussTitle").val();
                        if (discussTitle.trim() == "") {
                            alert("标题不能为空!");
                            return;
                        }
                        if (discussType == "1") {
                            var mainContent = mainUE.getContent();
                            if (mainContent.length <= 0) {
                                alert("内容不能为空!");
                                return;
                            }
                            $("#DiscussContent").remove();
                            $("#mainForm").append("<input type='hidden' name='DiscussContent' id='DiscussContent' value='" + mainContent + "' />");
                        } else {
                            if ($("#DiscussFileUrl").val() == "" || $("#DiscussOfficeFileUrl").val() == "") {
                                alert("必须上传文件!");
                                return;
                            }
                        }
                        $("#mainForm").submit();
                    });

                    $("#DiscussType").change(function () {
                        CommonCommentPageCreate.ChangeSelect(this);
                    });

                    $("#upload_file").WGXUploadFile({
                        action: '@Url.Action("UploadOfficeFile")',
                        params: 'ModuleCode=' + $("#ModuleCode").val(),
                        callback: function (fileId, data) {
                            if (data.success) {
                                $("#DiscussOfficeFileUrl").val(data.officeUrl);
                                $("#DiscussFileUrl").val(data.flashUrl);
                                $("#upload_file").WGXuploadFile("remove");
                            }
                            alert(data.message);
                        }
                    });

                    CommonCommentPageCreate.ChangeSelect($("#DiscussType"));
                }();
            })(CommonCommentPageCreate);
        });
    </script>
}

Lean/Areas/LeanManage/Views/CommonComment/Index.cshtml
@model PDM<IEnumerable<CommonComment>, CommonCommentCondition>
@{
    ViewBag.Title = "Index";
    string moduleCode = Model != null && Model.Condition != null ? Model.Condition.ModuleCode : "None";
}

@using (Html.BeginForm())
{
    <div class="panel panel-info">
        <div class="panel-heading clearfix">
            @Html.TextBlockFor(m => m.Condition.ModuleCode, "col-xs-12")
            @SharedTemplatesHelper.SearchBtnBlock()
        </div>
        
        <div class="panel-body">
            <div class="btn-group btn-group-sm">
                <a class="btn btn-default" href="@Url.Action("Create", "CommonComment")?ModuleCode=@(moduleCode)" ><span class="glyphicon glyphicon-plus"></span></a>
            </div>

            <table class="table show_table">
                <thead>
                    <tr>
                        <td>标题</td>
                        <td>发布时间</td>
                        <td>功能</td>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Data != null)
                    {
                        foreach (var item in Model.Data)
                        {
                            <tr>
                                <td>@(item.DiscussTitle)</td>
                                <td style="width: 200px;">@(item.DiscussDate.ToString("yyyy-MM-dd HH:mm:ss"))</td>
                                <td style="width: 100px;">
                                    <div class="btn-group btn-group-sm">
                                        <button class="btn btn-default" type="button" onclick="CommonCommentIndexPage.Edit(@(item.ID))"><span class="glyphicon glyphicon-pencil"></span></button>
                                        <button class="btn btn-default" type="button" onclick="CommonCommentIndexPage.Delete(@(item.ID)"><span class="glyphicon glyphicon-trash"></span></button>
                                    </div>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
        <div class="panel-footer">
            @if(Model != null && Model.Condition != null)
            {
                @Html.Pager(m => m.Condition.Pager)
            }
        </div>
    </div>
}

@section scripts {
    <script>
        $(function () {
            CommonCommentIndexPage = window.CommonCommentIndexPage || {};
            (function (_) {
                _.PageLoad = function () {

                }();

                _.Delete = function (id) {
                    WGX.ColorBox.Confirm("", "warn", "提示", "是否要删除该记录?", function () {
                        $.ajax({
                            url: '@Url.Action("Delete")',
                            data: 'id=' + id + "&moduleCode=@(moduleCode)",
                            dataType: "json",
                            type: "post",
                            success: function (data) {
                                if (data.success) {
                                    $("#btn_Search").click();
                                } else {
                                    alert(data.message);
                                }
                            },
                            error: function () {
                                alert("System Error!");
                            }
                        });
                    });
                }

                _.Edit = function (id) {
                    window.location.href = "@Url.Action("Edit", "CommonComment", null)/" + id + "?moduleCode=@(moduleCode)";
                }
            })(CommonCommentIndexPage);
        });
    </script>
}