Lean/Areas/LeanManage/Controllers/ManageHomeController.cs
using Lean.Filters;
using Microsoft.Practices.Unity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WGX.Lean.DbEntity;
using WGX.Lean.IBiz;

namespace Lean.Areas.LeanManage.Controllers
{
    public class ManageHomeController : PrivateController
    {
        [Dependency]
        public ICreateModel CreateModelBiz
        {
            get;
            set;
        }

        // GET: VolunteerManage/Home
        public ActionResult Index()
        {
            return View();
        }

        [CheckPower(false, Order = 11)]
        public ActionResult Registry()
        {
            var model = CreateModelBiz.GetFirst();
            return View(model);
        }

        [CheckPower(false, Order = 11)]
        [HttpPost]
        public ActionResult Registry(CreateModel entity)
        {
            if (ModelState.IsValid)
            {
                if (CreateModelBiz.CheckCreateModel(entity))
                {
                    if (CreateModelBiz.GetFirst() == null)
                    {
                        CreateModelBiz.Add(entity);
                    }
                    else
                    {
                        CreateModelBiz.Edit(entity);
                    }
                    if (!CreateModelBiz.HasError)
                    {
                        SetMessage("注册成功!");
                    }
                    else
                    {
                        ParseBizError(CreateModelBiz);
                    }
                }
                else
                {
                    SetMessage("验证码不匹配");
                }
            }
            return View(entity);
        }
    }
}

Lean/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Practices.Unity;
using WGX.Common.Enums;
using WGX.Common.Helper;
using WGX.Common.ModelBinder;
using WGX.Lean.IBiz;
using Lean.Filters;
using WGX.Lean.DbEntity;
using WGX.Lean.BizEntity.ViewModels;


namespace Lean
{
    public class UserController : PrivateController
    {
        [Dependency]
        public IUser UserBiz
        {
            get;
            set;
        }

        [Dependency]
        public IModule ModuleBiz
        {
            get;
            set;
        }

        [NeedLogin(false, Order = 11), CheckPower(false, Order = 12)]
        public ActionResult Login()
        {
            if (SessionHelper.Get<UserInfo>(SessionKeys.LoginUser) != null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        [NeedLogin(false, Order = 11), CheckPower(false, Order = 12)]
        public ActionResult Login([ModelBinder(typeof(SmartBinder))][Bind(Exclude = "ConfirmPwd, NewPassword, OldPassword")]LoginUser user)
        {
            var userInfo = UserBiz.Login(user);
            var result = false;
            var msg = "";
            long id = 0;
            bool isAdmin = false;
            if (null != userInfo)
            {
                SessionHelper.Set(SessionKeys.LoginUser, userInfo);
                var modules = ModuleBiz.GetModuleByUser(userInfo);
                if (modules != null)
                {
                    SessionHelper.Set(SessionKeys.UserMenus, modules);
                }
                result = true;
                msg = userInfo.UserName;
                isAdmin = userInfo.IsAdmin;
                id = userInfo.ID;
            }
            else
            {
                msg = UserBiz.Errors.Count > 0 ? UserBiz.Errors.FirstOrDefault().Value : "Login Failure!";
            }

            return Json(new { success = result, message = msg, id = id, IsAdmin = isAdmin }, JsonRequestBehavior.AllowGet);
        }

        [NeedLogin(Order = 11), CheckPower(false, Order = 12)]
        public ActionResult Logout()
        {
            bool result = false;
            if (SessionHelper.Remove(SessionKeys.LoginUser))
            {
                result = true;
            }
            return Json(new {success = result}, JsonRequestBehavior.AllowGet);
        }

        [CheckPower(false, Order = 11)]
        public ActionResult ChangePwd()
        {
            //var entity = CurrentUser;
            return View("ChangePassword");
        }

        [CheckPower(false, Order = 11)]
        [HttpPost]
        public ActionResult ChangePwd([ModelBinder(typeof(SmartBinder))][Bind(Include = "ConfirmPwd, NewPassword, OldPassword")]LoginUser entity)
        {
            var msg = "";
            var res = false;
            if (ModelState.IsValid)
            {
                res = UserBiz.ChangePwd(entity.OldPassword, entity.NewPassword);
                if (res)
                {
                    SetMessage("修改密码成功!");
                }
                else
                {
                    msg = UserBiz.Errors.FirstOrDefault().Value;
                }
            }
            return Json(new {success = res, message = msg}, "text/html", JsonRequestBehavior.AllowGet);
        }

        
    }
}

Lean/Views/Shared/BoolDropDownListBlock.cshtml
@model object
@{
    this.Layout = null;
    string propertyExpression = ViewBag.PropertyName;
    string containerClass = ViewBag.ContainerClass;
    bool IsNullable = ViewBag.IsNullable ?? false;

    var value = ModelMetadata.FromStringExpression(propertyExpression, ViewData);

    var items = new List<SelectListItem>() {
        new SelectListItem(){
             Value = "true",
              Text = ViewBag.TrueLabel,
              Selected = value != null && value.Model != null && (bool)value.Model
        },
        new SelectListItem(){
             Value = "false",
              Text = ViewBag.FalseLabel,
              Selected = value != null && value.Model != null && (bool)value.Model != true
        }
    };
    
    if (IsNullable)
    {
        items.Insert(0, new SelectListItem()
        {
            Value = "",
            Text = ViewBag.NullLabel
        });
    }

    RouteValueDictionary htmlAttributes = SharedTemplatesHelper.MargeClass(ViewBag);
    
}

<div class="@containerClass" style="margin-bottom: 15px;">
    @SharedTemplatesHelper.HorizontalLabel(ViewBag)
    @SharedTemplatesHelper.CreateHtmlObject(ViewBag, Html.DropDownList(propertyExpression, items, htmlAttributes))
    @*@Html.DropDownList(propertyExpression, items, htmlAttributes)*@
</div>

Lean/Views/Shared/ChangePassword.cshtml
@model LoginUser
@{
    Layout = "_SubPageLayout.cshtml";
    ViewBag.Title = "修改密码";
}

@using (Html.BeginForm("ChangePwd", "User", FormMethod.Post))
{
    <div class="container">
        <div class="row">
            @Html.PasswordBlockFor(m => m.OldPassword, "col-xs-12")
            @Html.ValidationMessageFor(m => m.OldPassword)
            @Html.PasswordBlockFor(m => m.NewPassword, "col-xs-12")
            @Html.ValidationMessageFor(m => m.NewPassword)
            @Html.PasswordBlockFor(m => m.ConfirmPwd, "col-xs-12")
            @Html.ValidationMessageFor(m => m.ConfirmPwd)
        </div>
        <div class="row">
            
        </div>
        <div class="panel-footer center">
            <div class="btn-group">
                <button class="btn btn-primary" type="button" id="btn_Save">保存</button>
                <button class="btn btn-default" type="button" onclick="WGX.ColorBox.Close()">关闭</button>
            </div>
        </div>
    </div>
    
}
@section scripts{
    <script>
        $(function() {
            $("#btn_Save").click(function() {
                var formdata = $("form").serialize();
                $.ajax({
                    url: '@Url.Action("ChangePwd", "User", new { area = ""})',
                    data: formdata,
                    type: 'post',
                    dataType: 'json',
                    success: function(data) {
                        if (data.success) {
                            top.window.location.reload();
                        } else {
                            alert(data.message);
                        }
                    }
                });
            });
        })
    </script>
}

Lean/Views/Shared/CheckBoxBlock.cshtml
@model object
@using System.Collections
@using System.Linq.Expressions

@{
    this.Layout = null;
    string propertyExpression = ViewBag.PropertyName;
    string containerClass = ViewBag.ContainerClass;
    string labelWidth = ViewBag.LabelWidth ?? "";
    if (!string.IsNullOrEmpty(labelWidth) && !labelWidth.Trim().EndsWith(";"))
    {
        labelWidth += ";";
    }
    if (string.IsNullOrEmpty(labelWidth))
    {
        labelWidth = "auto";
    }
}


<div class="@containerClass" style="margin-bottom: 15px;">
    @SharedTemplatesHelper.HorizontalLabel(ViewBag)
    @*@SharedTemplatesHelper.CreateHtmlObject(ViewBag, Html.CheckBox(propertyExpression))*@
    
    <div style="float:none; padding-top: 4px; padding-left:@(labelWidth)">
        @Html.CheckBox(propertyExpression)
    </div>
    @*@Html.CheckBox(propertyExpression)*@
</div>

Lean/Views/Shared/Denied.cshtml
@{
    ViewBag.Title = "拒绝访问";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>您没有 该页面/数据 的访问权限</h2>

Lean/Views/Shared/DoubleTimeSelector.cshtml
@model object
@{
    Layout = null;
    string propertyExpression = ViewBag.PropertyName;
    string containerClass = ViewBag.ContainerClass;
    string labelWidth = ViewBag.LabelWidth ?? "";
    if (!string.IsNullOrEmpty(labelWidth) && !labelWidth.Trim().EndsWith(";"))
    {
        labelWidth += ";";
    }
    string inputWidth = ViewBag.InputWidth ?? "";
    
    if (!string.IsNullOrEmpty(inputWidth) && !inputWidth.Trim().EndsWith(";"))
    {
        inputWidth += ";";
    }
    if (!string.IsNullOrEmpty(inputWidth))
    {
        inputWidth = "width:" + inputWidth;
    }
    string startName = ViewBag.StartProperty ?? "";
    string endName = ViewBag.EndProperty ?? "";

    RouteValueDictionary startHtmlAttributes = SharedTemplatesHelper.MargeClass(ViewBag, false);
    RouteValueDictionary endHtmlAttributes = SharedTemplatesHelper.MargeClass(ViewBag, false);
    startHtmlAttributes["style"] = "width: 48%; float:left;";
    endHtmlAttributes["style"] = "width: 48%;float:left;";
}

<div class="@containerClass" style="margin-bottom: 15px;">
    @SharedTemplatesHelper.HorizontalLabel(ViewBag)
    <div style="float: none; padding-left: @(labelWidth)">
        <div style="@(inputWidth)">
            @Html.TextBox(startName, null, startHtmlAttributes)
            <span style="float:left;width:4%;">-</span>
            @Html.TextBox(endName, null, endHtmlAttributes)
        </div>
    </div>
</div>

Lean/Views/Shared/DropdownBlock.cshtml
@model object
@using System.Collections

@{
    this.Layout = null;
    string propertyExpression = ViewBag.PropertyName;
    string containerClass = ViewBag.ContainerClass;
    
    var listItems = ViewData["DropDownBlock"] == null ? new List<SelectListItem>() : (IEnumerable<SelectListItem>)ViewData["DropDownBlock"];
    RouteValueDictionary htmlAttributes = SharedTemplatesHelper.MargeClass(ViewBag, false);
}

<div class="@containerClass" style="margin-bottom: 15px;">
    @SharedTemplatesHelper.HorizontalLabel(ViewBag)
    @SharedTemplatesHelper.CreateHtmlObject(ViewBag, Html.DropDownList(propertyExpression, listItems, htmlAttributes))
    @*<div style="float: none; padding-left: @(labelWidth)">
        @Html.DropDownList(propertyExpression, listItems, htmlAttributes)
    </div>*@
</div>

Lean/Views/Shared/FileUpload.cshtml
@model object
@{
    Layout = null;
    string propertyExpression = ViewBag.PropertyName;
    string containerClass = ViewBag.ContainerClass;
    string fileName = ViewBag.FileName;
    string labelWidth = ViewBag.LabelWidth ?? "";
    string btnWidth = ViewBag.ButtonWidth ?? "";
    string lineHeight = ViewBag.LineHeight ?? "";
    
    string marginTop = lineHeight;
    if (!string.IsNullOrEmpty(lineHeight))
    {
        if(lineHeight.Trim().EndsWith(";"))
        {
            lineHeight = lineHeight.Trim().Substring(0, lineHeight.Trim().Length - 1);
            marginTop = lineHeight;
        }
        lineHeight = string.Format("height: {0};", lineHeight.Trim());
        marginTop = string.Format("margin-top: -{0};", marginTop.Trim());
    }
    if (!string.IsNullOrEmpty(labelWidth) && !labelWidth.Trim().EndsWith(";"))
    {
        labelWidth += ";";
    }
    string inputWidth = ViewBag.InputWidth ?? "";
    
    if (!string.IsNullOrEmpty(inputWidth) && !inputWidth.Trim().EndsWith(";"))
    {
        inputWidth += ";";
    }
    if (!string.IsNullOrEmpty(inputWidth))
    {
        inputWidth = "width:" + inputWidth;
    }
    if (!string.IsNullOrEmpty(btnWidth) && btnWidth.Trim().EndsWith(";"))
    {
        btnWidth = btnWidth.Trim().Substring(0, btnWidth.Trim().Length - 1);
    }
    RouteValueDictionary htmlAttributes = SharedTemplatesHelper.MargeClass(ViewBag, false);
    htmlAttributes.Add("readonly", "readonly");
}

<div class="@containerClass" style="margin-bottom: 15px;">
    @SharedTemplatesHelper.HorizontalLabel(ViewBag)
    <div style="float: none; padding-right:@(btnWidth); padding-left: @(labelWidth)">
        <div style="@(inputWidth)">
            @Html.TextBox(propertyExpression, null, htmlAttributes)
        </div>
    </div>
    <div style="float:right; position: relative; width: @(btnWidth); @(marginTop) @(lineHeight)">
        <button type="button" class="btn" style="width: 100%;height: 100%;"><span>...</span></button>
        <input type="file" name="@(fileName)" class="color-add" id="@(fileName)" style="width: 100%;height: 100%;position:absolute;top:0px;opacity: 0; filter: alpha(opacity=0);" />
    </div>
</div>

Lean/Views/Shared/NewsCommonPublish.cshtml
@model CommonComment

@{
    ViewBag.Title = "Create";
    var content = Model != null ? Model.DiscussContent : "";
    var datas = PageDatas.GetInstance();
}
@Styles.Render("~/Content/ueditor/themes/iframe.css")
@using (Html.BeginForm())
{
    <div class="container">
        <div class="row" id="select_type">
            @Html.DropDownBlockFor(m => m.DiscussType, datas.GetEnumList(typeof(DiscussTypeEnum)), "col-xs-3")
        </div>
        <div class="row" id="EditDiscuss">
            <textarea id="mainContent" type="text/plain" style="width: 100%; height: 1000px;"></textarea>
        </div>
        <div class="row" id="UploadDiscuss">
            @Html.FileUploadBlockFor(m => m.DiscussOfficeFileUrl, "col-xs-6")
            @Html.HiddenFor(m => m.DiscussFileUrl)
        </div>
        <div class="panel-footer center">
            <div class="btn-group btn-group-sm">
                <button class="btn btn-primary" id="btnSave" value="Save" type="button"><span>保存</span></button>
                @SharedTemplatesHelper.ReturnToListBtn(Url);
            </div>
        </div>
    </div>
}

@section scripts{
    <script src="~/Content/ueditor/ueditor.config.js"></script>
    <script src="~/Content/ueditor/ueditor.all.js"></script>
    <script src="~/Content/ueditor/lang/zh-cn/zh-cn.js"></script>
    <script>
        $(function(){
            ManagerCommentCreatePage = window.ManagerCommentCreatePage || {};
            (function (_) {
                _.PageLoad = function () {
                    mainUE = UE.getEditor('mainContent', {
                        toolbars: [[
                        'fullscreen', 'source', '|', 'undo', 'redo', '|',
                        'bold', 'italic', 'underline', 'fontborder', 'strikethrough', 'superscript', 'subscript', 'removeformat', 'formatmatch', 'autotypeset', 'blockquote', 'pasteplain', '|', 'forecolor', 'backcolor', 'insertorderedlist', 'insertunorderedlist', 'selectall', 'cleardoc', '|',
                        'rowspacingtop', 'rowspacingbottom', 'lineheight', '|',
                        'customstyle', 'paragraph', 'fontfamily', 'fontsize', '|',
                        'directionalityltr', 'directionalityrtl', 'indent', '|',
                        'justifyleft', 'justifycenter', 'justifyright', 'justifyjustify', '|', 'touppercase', 'tolowercase', '|',
                        'link', 'unlink', 'anchor', '|', 'imagenone', 'imageleft', 'imageright', 'imagecenter', '|',
                        'simpleupload', 'insertimage', 'emotion', 'scrawl', 'insertvideo', 'music', 'attachment', 'map', 'gmap', 'insertframe', 'insertcode', 'webapp', 'pagebreak', 'template', 'background', '|',
                        'horizontal', 'date', 'time', 'spechars', 'snapscreen', 'wordimage', '|',
                        'inserttable', 'deletetable', 'insertparagraphbeforetable', 'insertrow', 'deleterow', 'insertcol', 'deletecol', 'mergecells', 'mergeright', 'mergedown', 'splittocells', 'splittorows', 'splittocols', 'charts', '|',
                        'preview', 'searchreplace', 'help'
                        ]]
                    });
                    mainUE.ready(function () {
                        mainUE.setContent("@Html.Raw(content)");
                    });

                    $("#btnSave").click(function () {
                        var mainContent = mainUE.getContent();
                        if (mainContent.length <= 0) {
                            alert("内容不能为空!");
                        }
                        $("#Content").remove();
                        $("form").append("<input type='hidden' name='Content' id='Content' value='" + mainContent + "' />")
                            .submit();
                    });

                    $("#DiscussType").change(function () {
                        var type = $(this).val();
                        if (type == "1") {
                            $("#UploadDiscuss").hide();
                            $("#EditDiscuss").show();
                        } else {
                            $("#UploadDiscuss").show();
                            $("#EditDiscuss").hide();
                        }
                    });
                }();
            })(ManagerCommentCreatePage);
        });
    </script>
}

Lean/Views/Shared/Pagination.cshtml
@model object

@{
    Layout = null;
    var pagination = (Pagination)ViewBag.Pagination;
    var pageItems = pagination.GetPageItems();
    var hiddenName = (string)ViewBag.HiddenName;
    var currPage = pagination.CurrPage - 1;
}

@if (pageItems != null && pageItems.Count > 0)
{
    <input type="hidden" name="@hiddenName" data-pager='true' value="@currPage" />
    <ul class="pagination pagination-sm">
        <li><span>共 @pagination.Total 笔 &nbsp;&nbsp;@pagination.TotalPage 页</span></li>
        @foreach (var item in pageItems)
        {
            var className = item.IsCurrPage ? "active" : "";
            var p = item.Page - 1;

            <li class="@className"><a href='javascript:void(0)' onclick="PaginationHelper.Set('@hiddenName',@p)">@item.Label</a></li>
        }
    </ul>
}

Lean/Views/Shared/PasswordBlock.cshtml
@model object
@{
    Layout = null;
    string propertyExpression = ViewBag.PropertyName;
    string containerClass = ViewBag.ContainerClass;

    RouteValueDictionary htmlAttributes = SharedTemplatesHelper.MargeClass(ViewBag);
    //if (!htmlAttributes.Any(q => q.Value.ToString().Contains("col-")))
    //{
    //    if (htmlAttributes.Keys.Contains("class"))
    //    {
    //        htmlAttributes["class"] += " col-xs-9";
    //    }
    //    else
    //    {
    //        htmlAttributes.Add("class", "col-xs-9");
    //    }
    //}
    //if (htmlAttributes.Keys.Contains("style"))
    //{
    //    if (!htmlAttributes["style"].ToString().Trim().Contains("width:"))
    //    {
    //        if (!htmlAttributes["style"].ToString().Trim().EndsWith(";"))
    //        {
    //            htmlAttributes["style"] += ";";
    //        }
    //        htmlAttributes["style"] += "width: 70%;";
    //    }
    //}
    //else
    //{
    //    htmlAttributes.Add("style", "width: 70%;");
    //}
    var metadata = ModelMetadata.FromStringExpression(propertyExpression, Html.ViewData);
}

<div class="@containerClass" style="margin-bottom: 15px;">
    @SharedTemplatesHelper.HorizontalLabel(ViewBag)
    @SharedTemplatesHelper.CreateHtmlObject(ViewBag, Html.Password(propertyExpression, null, htmlAttributes))
    @*@Html.Password(propertyExpression, null, htmlAttributes)*@
</div>

Lean/Views/Shared/TextBlock.cshtml
@model object
@{
    Layout = null;
    string propertyExpression = ViewBag.PropertyName;
    string containerClass = ViewBag.ContainerClass;
    RouteValueDictionary htmlAttributes = SharedTemplatesHelper.MargeClass(ViewBag);
    
    var metadata = ModelMetadata.FromStringExpression(propertyExpression, Html.ViewData);
    string fmt = ViewBag.Formart;
    if (string.IsNullOrWhiteSpace(fmt)
        && (
            metadata.ModelType == typeof(DateTime)
            || metadata.ModelType == typeof(DateTime?))
        )
    {
        fmt = @"{0:yyyy\/MM\/dd}";
    }
}

<div class="@containerClass" style="margin-bottom: 15px;">
    @SharedTemplatesHelper.HorizontalLabel(ViewBag)
    @SharedTemplatesHelper.CreateHtmlObject(ViewBag, Html.TextBox(propertyExpression, null, fmt, htmlAttributes))
    @*<div style="float:none; padding-left:@(labelWidth);">
        @Html.TextBox(propertyExpression, null, fmt, htmlAttributes)
    </div>*@
</div>

Lean/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="~/Content/styles.css" />
    <link type="text/css" href="~/Content/ui-lightness/jquery-ui-1.8.16.custom.css" rel="stylesheet" />
    @{
        var datas = PageDatas.GetInstance();
        var area = ViewContext.RouteData.DataTokens["area"];
        
        var menus = datas.GetModules(area);
        if (area == null)
        {
            menus = menus.Where(q => !q.IsBack).ToList();
        }
        else
        {
            menus = menus.Where(q => q.IsBack).ToList();
        }
        var showMenus = menus.Where(q => q.IsMenu && q.ParentID == 0 && q.Valid);
        var currentMenu = TempData["CurrentMenu"] as BaseModule;
        var currentUser = datas.CurrentUserBiz.CurrentUser;
        string msg = TempData["ShowMessage"]== null ? "" : TempData["ShowMessage"].ToString();
        
    }
    @RenderSection("styles", required: false)
</head>

<body>
    <div id="page">
        <div id="header_home">
            <div id="headerInside">
                <div class="logo">
                    <a href="@Url.Action("Index", "Home", new { area = "" })" title="Home">
                        <img src="~/Content/images/logo.png" width="308" height="92" alt="Lean Enterprise Institute" title="Lean Enterprise Institute" />
                        <img src="~/Content/images/pre_logo.png" height="92" />
                    </a>
                </div>
                <div class="rightHeaderBox">
                    <div class="grid_head1">
                        <ul id="login_ul" class="utility-nav" style="@(currentUser ==null ? "" : "display:none;")">
                            @using (Html.BeginForm("Login", "User", FormMethod.Post, new { id = "LoginForm" }))
                            { 
                                <li class="title">User Name:</li>
                                <li class="input"><input name="UserCode" value="" type="text" id="UserCode" /></li>
                                <li class="title">Password:</li>
                                <li class="input"><input type="password" value="" name="Password" id="Password" /></li>
                                <li class="button"><div class="btn-group btn-group-xs"><button class="btn btn-link" type="button" value="Login" id="btnLogin">Login</button></div></li>
                            }
                        </ul>
                        <ul id="user_ul" class="utility-nav" style="@(currentUser == null ? "display:none;" : "")">
                            @if (currentUser != null)
                            {
                                <li class="username_show">Hello, <a href="@Url.Action("UserCenter", "Home", new { area = "", id = currentUser.ID })">@(currentUser.UserName)</a></li>
                                @*<li class="changepwd_show"></li>*@
                                if (currentUser.IsAdmin)
                                {
                                    if (area == null) { 
                                        <li class="linkback"><div class="btn-group btn-group-xs"><a class="btn btn-link" href="@Url.Action("Index", "ManageHome", new { area = "LeanManage" })"><span>Back Manage</span></a></div></li>
                                    }
                                    else
                                    {
                                        <li class="linkback"><div class="btn-group btn-group-xs"><a class="btn btn-link" href="@Url.Action("Index", "Home", new { area = "" })"><span>To Front</span></a></div></li>
                                    }
                                    
                                    <li class="linkback"><div class="btn-group btn-group-xs"><button class="btn btn-link" id="ChangeRegCode"><span>Change Registry Code</span></button></div></li>
                                }
                                <li class="logout"><div class="btn-group btn-group-xs"><button class="btn btn-link" type="button" id="btnLogout" value="Logout"><span class="last-item">Logout</span></button></div></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
            <div id="menuEnvelope">
                <div id="menu">
                    @foreach (var menu in showMenus)
                    {
                        <div class="menu_push">
                            @if (currentMenu != null && menu.ModuleCode.ToUpper() == currentMenu.ModuleCode.ToUpper())
                            {
                                <span>@(menu.ModuleName)</span>
                            }
                            else
                            {
                                <a href="@(menu.ModuleUrl)">@(menu.ModuleName)</a>
                            }
                            @{
                                var subMenus = menus.Where(q => q.ParentID == menu.ID && q.IsMenu && q.Valid);
                            }
                            @if (subMenus.Any())
                            {
                                <div style="position: relative; width: 100%;">
                                    <div class="menu_submenu" style="position: absolute; width: 100%;">
                                        @foreach (var sub in subMenus)
                                        {
                                            <a class="submenu_a" href="@(sub.ModuleUrl)">@(sub.ModuleName)</a>
                                        }
                                    </div>
                                </div>
                            }
                        </div>
                    }
                    @if(showMenus.Count() == 0)
                    { 
                    <div class="menu_push"><span>Home</span></div>
                    <div class="menu_push">
                        <a href="WhoWeAre/index.htm" >111</a>
                        <div style="position:relative;">
                            <div class="menu_submenu" style="position:absolute;">
                                <a class="submenu_a" href="#">submenu1</a>
                                <a class="submenu_a" href="#">submenu2</a>
                                <a class="submenu_a" href="#">submenu3</a>
                                <a class="submenu_a" href="#">submenu4</a>
                                <a class="submenu_a" href="#">submenu5</a>
                            </div>
                        </div>
                    </div>
                    <div class="menu_push"><a href="#" >222</a></div>
                    <div class="menu_push">
                        <a href="#" >333</a>
                        <div style="position:relative;">
                            <div class="menu_submenu" style="position:absolute;">
                                <a class="submenu_a" href="#">submenu1</a>
                                <a class="submenu_a" href="#">submenu2</a>
                                <a class="submenu_a" href="#">submenu3</a>
                                <a class="submenu_a" href="#">submenu4</a>
                                <a class="submenu_a" href="#">submenu5</a>
                            </div>
                        </div>
                    </div>
                    <div class="menu_push"><a href="#" >444</a></div>
                    }
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
        </div>
        <div class="container body-footer">

        </div>
    </div>
    
    @Scripts.Render("~/bundles/common")
    @if (!string.IsNullOrWhiteSpace(msg))
    {
        <script>
            alert("@msg");
        </script>
    }
    @RenderSection("scripts", required: false)
</body>
</html>